name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker auth for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push image with Cloud Build
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/yt-metadata:${{ github.sha }}
          echo "Building image $IMAGE"
          gcloud builds submit --tag $IMAGE

      - name: Deploy to Cloud Run (set YOUTUBE_COOKIE as base64)
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          IMAGE=gcr.io/${{ secrets.GCP_PROJECT_ID }}/yt-metadata:${{ github.sha }}
          SERVICE_NAME=yt-metadata
          REGION=asia-southeast1

          # Base64 encode secret to a single-line safe env var
          COOKIE_B64=$(echo "${{ secrets.YOUTUBE_COOKIE }}" | base64 -w 0)

          echo "Deploying $SERVICE_NAME -> $REGION"
          gcloud run deploy "$SERVICE_NAME" \
            --image "$IMAGE" \
            --region "$REGION" \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars "YOUTUBE_COOKIE=${COOKIE_B64}"
